// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mock;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mock.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20251026174918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("message_id"));

                    b.Property<bool?>("ConfirmArrival")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("hasResponse")
                        .HasColumnType("boolean");

                    b.Property<int>("helped_id")
                        .HasColumnType("integer");

                    b.Property<bool>("isDone")
                        .HasColumnType("boolean");

                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<int?>("volunteer_id")
                        .HasColumnType("integer");

                    b.HasKey("message_id");

                    b.HasIndex("helped_id");

                    b.HasIndex("volunteer_id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Repository.Entites.Helped", b =>
                {
                    b.Property<int>("helped_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("helped_id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("helped_first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("helped_last_name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tel")
                        .HasColumnType("text");

                    b.HasKey("helped_id");

                    b.ToTable("Helpeds");
                });

            modelBuilder.Entity("Repository.Entites.KnowledgeCategory", b =>
                {
                    b.Property<int>("ID_knowledge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_knowledge"));

                    b.Property<string>("describtion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_knowledge");

                    b.ToTable("KnowledgeCategories");
                });

            modelBuilder.Entity("Repository.Entites.My_areas_of_knowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ID_knowledge")
                        .HasColumnType("integer");

                    b.Property<int>("volunteer_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ID_knowledge");

                    b.HasIndex("volunteer_id");

                    b.ToTable("areas_Of_Knowledges");
                });

            modelBuilder.Entity("Repository.Entites.Response", b =>
                {
                    b.Property<int>("response_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("response_id"));

                    b.Property<string>("context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("message_id")
                        .HasColumnType("integer");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.HasKey("response_id");

                    b.HasIndex("message_id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Repository.Entites.Volunteer", b =>
                {
                    b.Property<int>("volunteer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("volunteer_id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("assignment_count")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("end_time")
                        .HasColumnType("interval");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("start_time")
                        .HasColumnType("interval");

                    b.Property<string>("tel")
                        .HasColumnType("text");

                    b.Property<string>("volunteer_first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("volunteer_last_name")
                        .HasColumnType("text");

                    b.HasKey("volunteer_id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("Repository.Entites.Helped", "Helped")
                        .WithMany()
                        .HasForeignKey("helped_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entites.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("volunteer_id");

                    b.Navigation("Helped");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Repository.Entites.My_areas_of_knowledge", b =>
                {
                    b.HasOne("Repository.Entites.KnowledgeCategory", "KnowledgeCategory")
                        .WithMany("Volunteers")
                        .HasForeignKey("ID_knowledge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entites.Volunteer", "Volunteer")
                        .WithMany("areas_of_knowledge")
                        .HasForeignKey("volunteer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeCategory");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Repository.Entites.Response", b =>
                {
                    b.HasOne("Message", "Message")
                        .WithMany()
                        .HasForeignKey("message_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Repository.Entites.KnowledgeCategory", b =>
                {
                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("Repository.Entites.Volunteer", b =>
                {
                    b.Navigation("areas_of_knowledge");
                });
#pragma warning restore 612, 618
        }
    }
}
